# Generated by Django 5.2.1 on 2025-05-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_visitor_delete_visitorappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='location_history',
            field=models.JSONField(blank=True, default=list, help_text='List of locations (departments) visited by the visitor, in order.'),
        ),
    ]
